services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password.txt
    environment:
      POSTGRES_DB: buildbot
      POSTGRES_USER: buildbot
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password.txt
    logging:
      driver: local
    restart: unless-stopped

  buildbot:
    build:
      context: .
      dockerfile: master/Dockerfile
    depends_on:
      - db
    ports:
      - "9990:9990"
    volumes:
      - buildbot-gitpoller:/buildbot/master/gitpoller-llvm-workdir
      - ${HALIDE_BB_MASTER_ARTIFACTS_DIR:-./data/artifacts}:/artifacts
    secrets:
      - db_password.txt
      - github_token.txt
      - halide_bb_pass.txt
      - webhook_token.txt
      - buildbot_www_pass.txt
    environment:
      HALIDE_BB_MASTER_ARTIFACTS_DIR: /artifacts
      HALIDE_BB_MASTER_SECRETS_DIR: /run/secrets
      HALIDE_BB_MASTER_DB_URL: "postgresql://buildbot:{DB_PASSWORD}@db/buildbot"
    logging:
      driver: local
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - ${HALIDE_BB_MASTER_ARTIFACTS_DIR:-./data/artifacts}:/artifacts:ro
    logging:
      driver: local
    restart: unless-stopped

volumes:
  buildbot-gitpoller:
  caddy-data:
  caddy-config:
  db-data:

secrets:
  db_password.txt:
    file: ./secrets/db_password.txt
  github_token.txt:
    file: ./secrets/github_token.txt
  halide_bb_pass.txt:
    file: ./secrets/halide_bb_pass.txt
  webhook_token.txt:
    file: ./secrets/webhook_token.txt
  buildbot_www_pass.txt:
    file: ./secrets/buildbot_www_pass.txt
