services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password.txt
    environment:
      POSTGRES_DB: buildbot
      POSTGRES_USER: buildbot
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password.txt
    logging:
      driver: local
    restart: unless-stopped

  buildbot:
    build:
      context: .
      dockerfile: master/Dockerfile
    depends_on:
      - db
    ports:
      - "9990:9990"
    secrets:
      - db_password.txt
      - github_token.txt
      - halide_bb_pass.txt
      - webhook_token.txt
      - buildbot_www_pass.txt
    environment:
      HALIDE_BB_MASTER_SECRETS_DIR: /run/secrets
      HALIDE_BB_MASTER_DB_URL: "postgresql://buildbot:{DB_PASSWORD}@db/buildbot"
    logging:
      driver: local
    restart: unless-stopped

  pypi:
    image: pypiserver/pypiserver:v2.4.0
    volumes:
      - ${HALIDE_BB_PYPI_PACKAGES_DIR:-./data/packages}:/data/packages
    secrets:
      - pypi_htpasswd.txt
    command: run -P /run/secrets/pypi_htpasswd.txt -a update --backend cached-dir /data/packages
    logging:
      driver: local
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    logging:
      driver: local
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
  db-data:

secrets:
  db_password.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/db_password.txt
  github_token.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/github_token.txt
  halide_bb_pass.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/halide_bb_pass.txt
  webhook_token.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/webhook_token.txt
  buildbot_www_pass.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/buildbot_www_pass.txt
  pypi_htpasswd.txt:
    file: ${HALIDE_BB_MASTER_SECRETS_DIR:-./secrets}/pypi_htpasswd.txt
