[project]
name = "master"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "buildbot-www",
    "buildbot~=4.0",
    "psycopg2-binary~=2.9", # PostgreSQL database driver
    "treq>=25.5", # required by GitHubStatusPush
    "twisted>=23.10",
]
